x-airflow-common: &airflow-common
    build:
        context: ../../docker/03_orchestration
        dockerfile: Dockerfile
    image: rakuten-airflow:2.11.0-slim-py3.12
    env_file: ../../.env
    environment: &airflow-common-env
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@db_airflow/${AIRFLOW_DB_NAME}
        AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
        AIRFLOW__CORE__LOAD_EXAMPLES: "False"
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
        PYTHONPATH: /opt/airflow:/opt/airflow/src
        MLFLOW_TRACKING_URI: http://rakuten-mlflow:5000

        # MinIO (S3)
        AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
        AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
        MLFLOW_S3_ENDPOINT_URL: http://rakuten-minio:9000
        AIRFLOW__AWS__S3_ENDPOINT_URL: http://rakuten-minio:9000

        # Rakuten DB (Optuna storage)
        RAKUTEN_DB_HOST: postgres
        RAKUTEN_DB_PORT: 5432

        # Data paths (data/ monté sur /data dans le container)
        DATA_DIR: /data
        RAW_DATA_DIR: /data/raw
        PROCESSED_DATA_DIR: /data/processed
        IMAGES_DIR: /data/raw/images
        REPO_DIR: /opt/airflow/repo

    volumes:
        - ../../dags:/opt/airflow/dags
        - ../../src:/opt/airflow/src
        - ../../data:/data # ../../data:/opt/airflow/data
        - airflow_logs:/opt/airflow/logs
        - ../../:/opt/airflow/repo

    user: "${AIRFLOW_UID:-1000}:0"
    depends_on:
        airflow-init:
            condition: service_completed_successfully

services:
    # BDD
    db_airflow:
        image: postgres:17-alpine
        container_name: rakuten_db_airflow
        restart: unless-stopped
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: ${AIRFLOW_DB_USER}
            POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
            POSTGRES_DB: ${AIRFLOW_DB_NAME}
        volumes:
            - pg_airflow_data:/var/lib/postgresql/data
        networks:
            - rakuten_net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME}",
                ]
            interval: 10s
            retries: 5

    # Init Container
    airflow-init:
        build:
            context: ../../docker/03_orchestration
            dockerfile: Dockerfile
        image: rakuten-airflow:2.11.0-slim-py3.12
        container_name: rakuten_airflow_init
        depends_on:
            db_airflow:
                condition: service_healthy
        env_file: ../../.env
        environment:
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@db_airflow/${AIRFLOW_DB_NAME}
            AIRFLOW__CORE__EXECUTOR: LocalExecutor
        entrypoint: /bin/bash
        command:
            - -c
            - |
                airflow db migrate &&
                (airflow users create \
                  --username "${AIRFLOW_ADMIN_USER}" \
                  --password "${AIRFLOW_ADMIN_PASSWORD}" \
                  --firstname youssef \
                  --lastname bengala \
                  --role Admin \
                  --email "${AIRFLOW_ADMIN_EMAIL}" 2>/dev/null || echo "User already exists") && airflow connections add minio_s3 \
                            --conn-type aws \
                            --conn-login "${MINIO_ROOT_USER}" \
                            --conn-password "${MINIO_ROOT_PASSWORD}" \
                            --conn-extra '{"endpoint_url": "http://rakuten-minio:9000"}' 2>/dev/null || true
        networks:
            - rakuten_net

    # Webserver
    airflow-webserver:
        <<: *airflow-common
        container_name: rakuten_airflow_webserver
        restart: unless-stopped
        command: airflow webserver
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 30s
            retries: 3
        networks:
            - rakuten_net

    # Scheduler
    airflow-scheduler:
        <<: *airflow-common
        container_name: rakuten_airflow_scheduler
        restart: unless-stopped
        command: airflow scheduler
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "airflow jobs check --job-type SchedulerJob --hostname $(hostname)",
                ]
            interval: 30s
            retries: 5
        networks:
            - rakuten_net

volumes:
    pg_airflow_data:
        name: rakuten_vol_airflow_db
    airflow_logs:
        name: rakuten_vol_airflow_logs

networks:
    rakuten_net:
        external: true
